[package]
name = "druid-icon"
version = "0.1.0"
authors = ["Christian Perez-Llamas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "^0.6"

