[package]
name = "kiro-synth-core"
version = "0.1.0"
authors = ["Christian Perez Llamas"]
edition = "2018"

[dependencies]
num-traits = { version = "0.2", default-features = false, features = ["libm"] }
libm = "0.2.1"

generic-array = "0.14.2"

[dev-dependencies]
assert_approx_eq = "1.1.0"